
@Host =  http://localhost:1336/api/queue

###
post {{Host}}/addFull
Content-Type:application/json

{
    "title":"user-service",
    "content":"hi it word"
}

###

delete {{Host}}/user-service

###
post {{Host}}
Content-Type:application/json

{
    "title":"buck-service",
    "content":"hello this it my word"
}

###
post {{Host}}/user-service


###
post {{Host}}/pop/buck-service
