

@Host =  http://localhost:1336/api/redis


###
post {{Host}}
Content-Type: application/json;

{"key":"sendEmail",
 "value":"messages on"
}

###
###
post {{Host}}
Content-Type: application/json

{"name":"payment",
   "item":"it pament"
}
###
get {{Host}}/payment

###
put {{Host}}
Content-Type: application/json

{
   "key":"payment",
   "value":"was it pament"

}