

@Host =  http://localhost:1337/api/users

### 
get http://localhost:1337

###
get {{Host}}
###
get {{Host}}/1

###
POST {{Host}}
Content-Type: application/json

{

"name":"nguyên hữu đăng",
"age":86,
"address":"hà nội",
"salary":40000,
"email":"lam123@gmail.com",
"password":"hometour123rcA@",
"phone":"6598453495"


}

###
put {{Host}}/25
Content-Type: application/json

{

"name":"nguyen hữu bảo",
"age":17,
"address":"hà tĩnh",
"salary":1000,
"email":"baothptdl123@gmail.com",
"password":"123456a@",
"phone":"1234567"


}

###
delete {{Host}}/23