

@Host: http://localhost:1337/api/users

### 
get http://localhost:1337/api/users
###
get http://localhost:1337/api/users/5

###
POST http://localhost:1337/api/users
Content-Type: application/json

{

"name":"phong kha 12345",
"age":86,
"address":"hà nội",
"salary":40000,
"email":"lam123@gmail.com",
"password":"123456a@",
"phone":"6598453495"


}

###
put http://localhost:1337/api/users/5
Content-Type: application/json

{

"name":"nguyen yen",
"age":34,
"address":"hà nội",
"salary":40000,
"email":"hoang23@gmail.com",
"password":"123456a@",
"phone":"1234567"


}

###
delete http://localhost:1337/api/users/5