
@Host:http://localhost:1337/api/users

###
get http://localhost:1336/api/users
###
get http://localhost:1336/api/users/30
###
post http://localhost:1336/api/users
Content-Type: application/json

{
      "id": 30,
      "name": "nguyễn hữu đăng",
      "age": 55,
      "address": "ha noi",
      "salary": 1000,
      "email": "dang345@gmail.com",
      "password": "123456a@"

}

###
put http://localhost:1336/api/users
Content-Type: application/json

{
      "id": 30,
      "name": "nguyễn hữu đăng",
      "age": 55,
      "address": "ha noi                                            ",
      "salary": 1000,
      "email": "dang345@gmail.com",
      "password": "123456a@"

}
###
get http://localhost:1336/api/users